- name: Update apt and Docker on gaming laptop
  hosts: laptops
  become: true
  gather_facts: true

  tasks:
    - ansible.builtin.import_tasks: tasks/apt-update-and-reboot.yml

    - ansible.builtin.import_tasks: tasks/update-docker-compose-stacks.yml

    - ansible.builtin.import_tasks: tasks/prune-docker-images.yml
